# Generated by Django 2.1.3 on 2018-11-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRLife.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TR-01', max_length=10)),
                ('serial_number', models.CharField(max_length=20)),
                ('install_date', models.DateField()),
                ('voltage', models.FloatField(default=138.0)),
                ('nominal_power', models.FloatField(default=12.5)),
                ('class_temperature', models.IntegerField(default=55)),
                ('path_name', models.CharField(max_length=20)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRLife.Substation')),
            ],
        ),
    ]
